version: "3.9"

x-aws-loadbalancer: ${ADCU_LOADBALANCER_ARN}

networks:
  default:
    external: true
    name: ${ADCU_SECURITY_GROUP_ID}

services:

  aline-gateway:
    image: stephenfreed/aline-gateway:v0.1.0
    container_name: aline-gateway
    ports:
      - 8080:8080
    environment:
      - DOCKER0_IP=${ADCU_LOADBALANCER_DNS}
      - USER_PORT=${ADCU_USER_PORT}
      - UNDERWRITER_PORT=${ADCU_UNDERWRITER_PORT}
      - BANK_PORT=${ADCU_BANK_PORT}
      - TRANSACTION_PORT=${ADCU_TRANSACTION_PORT}
      - ACCOUNT_PORT=${ADCU_ACCOUNT_PORT}

  aline-account-microservice:
    image: stephenfreed/aline-account-microservice:v0.1.0
    container_name: aline-account-microservice
    ports:
      - 8074:8074
    environment:
      - DB_USERNAME=${ADCU_DB_USERNAME}
      - DB_PASSWORD=${ADCU_DB_PASSWORD}
      - DB_CONTAINER_NAME=${ADCU_DB_CONTAINER_NAME}
      - SECRET_KEY=${ADCU_SECRET_KEY}

  aline-bank-microservice:
    image: stephenfreed/aline-bank-microservice:v0.1.0
    container_name: aline-bank-microservice
    ports:
      - 8072:8072
    environment:
      - DB_USERNAME=${ADCU_DB_USERNAME}
      - DB_PASSWORD=${ADCU_DB_PASSWORD}
      - DB_CONTAINER_NAME=${ADCU_DB_CONTAINER_NAME}
      - SECRET_KEY=${ADCU_SECRET_KEY}

  aline-transaction-microservice:
    image: stephenfreed/aline-transaction-microservice:v0.1.0
    container_name: aline-transaction-microservice
    ports:
      - 8073:8073
    environment:
      - DB_USERNAME=${ADCU_DB_USERNAME}
      - DB_PASSWORD=${ADCU_DB_PASSWORD}
      - DB_CONTAINER_NAME=${ADCU_DB_CONTAINER_NAME}
      - SECRET_KEY=${ADCU_SECRET_KEY}

  aline-underwriter-microservice:
    image: stephenfreed/aline-underwriter-microservice:v0.1.0
    container_name: aline-underwriter-microservice
    ports:
      - 8071:8071
    environment:
      - DB_USERNAME=${ADCU_DB_USERNAME}
      - DB_PASSWORD=${ADCU_DB_PASSWORD}
      - DB_CONTAINER_NAME=${ADCU_DB_CONTAINER_NAME}
      - SECRET_KEY=${ADCU_SECRET_KEY}

  aline-user-microservice:
    image: stephenfreed/aline-user-microservice:v0.1.0
    container_name: aline-user-microservice
    ports:
      - 8070:8070
    environment:
      - DB_USERNAME=${ADCU_DB_USERNAME}
      - DB_PASSWORD=${ADCU_DB_PASSWORD}
      - DB_CONTAINER_NAME=${ADCU_DB_CONTAINER_NAME}
      - SECRET_KEY=${ADCU_SECRET_KEY}
