version: "3.9"

networks:
  aline-bridge:
    name: aline-bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.20.0/24
          gateway: 172.20.20.1

volumes:
  alinedb:

services:

  aline-gateway:
    image: stephenfreed/aline-gateway:v0.1.0
    container_name: aline-gateway
    ports:
      - 8080:8080
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DOCKER0_IP=172.20.20.1

  aline-account-microservice:
    image: stephenfreed/aline-account-microservice:v0.1.0
    container_name: aline-account-microservice
    ports:
      - 172.20.20.1:8074:8074
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DB_USERNAME=${CIRRUS_DB_USERNAME}
      - DB_PASSWORD=${CIRRUS_DB_PASSWORD}
      - DB_CONTAINER_NAME=${CIRRUS_DB_CONTAINER_NAME}
      - SECRET_KEY=${CIRRUS_SECRET_KEY}

  aline-bank-microservice:
    image: stephenfreed/aline-bank-microservice:v0.1.0
    container_name: aline-bank-microservice
    ports:
      - 172.20.20.1:8072:8072
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DB_USERNAME=${CIRRUS_DB_USERNAME}
      - DB_PASSWORD=${CIRRUS_DB_PASSWORD}
      - DB_CONTAINER_NAME=${CIRRUS_DB_CONTAINER_NAME}
      - SECRET_KEY=${CIRRUS_SECRET_KEY}

  aline-transaction-microservice:
    image: stephenfreed/aline-transaction-microservice:v0.1.0
    container_name: aline-transaction-microservice
    ports:
      - 172.20.20.1:8073:8073
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DB_USERNAME=${CIRRUS_DB_USERNAME}
      - DB_PASSWORD=${CIRRUS_DB_PASSWORD}
      - DB_CONTAINER_NAME=${CIRRUS_DB_CONTAINER_NAME}
      - SECRET_KEY=${CIRRUS_SECRET_KEY}

  aline-underwriter-microservice:
    image: stephenfreed/aline-underwriter-microservice:v0.1.0
    container_name: aline-underwriter-microservice
    ports:
      - 172.20.20.1:8071:8071
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DB_USERNAME=${CIRRUS_DB_USERNAME}
      - DB_PASSWORD=${CIRRUS_DB_PASSWORD}
      - DB_CONTAINER_NAME=${CIRRUS_DB_CONTAINER_NAME}
      - SECRET_KEY=${CIRRUS_SECRET_KEY}

  aline-user-microservice:
    image: stephenfreed/aline-user-microservice:v0.1.0
    container_name: aline-user-microservice
    ports:
      - 172.20.20.1:8070:8070
    networks:
      - aline-bridge
    depends_on:
      - aline-mysql
    environment:
      - DB_USERNAME=${CIRRUS_DB_USERNAME}
      - DB_PASSWORD=${CIRRUS_DB_PASSWORD}
      - DB_CONTAINER_NAME=${CIRRUS_DB_CONTAINER_NAME}
      - SECRET_KEY=${CIRRUS_SECRET_KEY}

  aline-mysql:
    image: mysql:8.0.28
    container_name: aline-mysql
    networks:
      aline-bridge:
        aliases:
          - aline-mysql
    security_opt:
      - seccomp:unconfined
    volumes:
      - alinedb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CIRRUS_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=alinedb
      - MYSQL_USER=${CIRRUS_MYSQL_USER}
      - MYSQL_PASSWORD=${CIRRUS_MYSQL_PASSWORD}

