server:
  port: 8080

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true

app:
  gateway:
    service-host: "http://${DOCKER0_IP}"
    path-prefix: "/api"
    routes:
      - id: "user"
        port: ${USER_PORT}  # 8070
        paths:
          - "@/users"
          - "@/users/{segment}"
          - "@/users/{segment}/profile"
          - "@/users/{segment}/avatar"
          - "@/login"
          - "/login"
      - id: "underwriter"
        port: ${UNDERWRITER_PORT}  # 8071
        paths:
          - "@/applicants"
          - "@/applications"
          - "@/applicants/{segment}"
          - "@/applications/{segment}"
      - id: "bank"
        port: ${BANK_PORT}  # 8072
        paths:
          - "@/members"
          - "@/members/{segment}"
          - "@/branches"
          - "@/banks"
          - "@/banks/routing"
          - "@/banks/routing/{segment}"
          - "@/banks/id"
          - "@/banks/id/{segment}"
      - id: "transaction"
        port: ${TRANSACTION_PORT}  # 8073
        paths:
          - "@/transactions"
          - "@/transactions/{segment}"
          - "@/members/{segment}/transactions"
          - "@/accounts/{segment}/transactions"
      - id: "account"
        port: ${ACCOUNT_PORT}  # 8074
        paths:
          - "@/accounts"
          - "@/accounts/{segment}"
          - "@/members/{segment}/accounts"
    portal-origins:
      - "http://localhost:4200"
      - "http://localhost:3007"
      - "http://localhost:3000"
